"""Print & Export Templates — Phase 6
Generates printable HTML and downloadable Excel/CSV for:
  6.1 Ingredient list
  6.2 Recipe card
  6.3 Stock count sheet
  6.4 Purchase order
  6.5 Excel export (competitor-compatible)
"""
from fastapi import APIRouter, HTTPException, Depends, Query
from fastapi.responses import HTMLResponse, StreamingResponse, JSONResponse
from core.database import db
from core.dependencies import get_current_user, check_venue_access
from datetime import datetime, timezone
import io
import csv
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/print", tags=["Print & Export Templates"])


# ═══════════════════════ SHARED HELPERS ═══════════════════════

def _html_wrapper(title: str, body: str, venue_name: str = "") -> str:
    """Wraps body HTML in a print-ready full page."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  @media print {{ @page {{ margin: 15mm; }} body {{ -webkit-print-color-adjust: exact; }} }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Inter', 'Segoe UI', sans-serif; font-size: 11px; color: #18181b; line-height: 1.5; padding: 20px; }}
  .header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #18181b; padding-bottom: 10px; margin-bottom: 16px; }}
  .header h1 {{ font-size: 18px; font-weight: 700; }}
  .header .meta {{ text-align: right; font-size: 10px; color: #71717a; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th {{ background: #f4f4f5; text-align: left; padding: 6px 8px; border: 1px solid #d4d4d8; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; }}
  td {{ padding: 6px 8px; border: 1px solid #e4e4e7; font-size: 11px; }}
  tr:nth-child(even) {{ background: #fafafa; }}
  .totals {{ margin-top: 16px; text-align: right; font-size: 13px; font-weight: 600; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 9px; font-weight: 600; }}
  .badge-green {{ background: #dcfce7; color: #166534; }}
  .badge-red {{ background: #fee2e2; color: #991b1b; }}
  .badge-yellow {{ background: #fef9c3; color: #854d0e; }}
  .recipe-section {{ margin-top: 20px; }}
  .recipe-section h2 {{ font-size: 14px; border-bottom: 1px solid #d4d4d8; padding-bottom: 4px; margin-bottom: 8px; }}
  .kv {{ display: flex; gap: 4px; margin-bottom: 4px; }}
  .kv .label {{ font-weight: 600; min-width: 140px; color: #71717a; }}
  .footer {{ margin-top: 30px; border-top: 1px solid #d4d4d8; padding-top: 8px; font-size: 9px; color: #a1a1aa; display: flex; justify-content: space-between; }}
  .allergens {{ display: flex; gap: 6px; flex-wrap: wrap; margin-top: 4px; }}
  .allergen-badge {{ padding: 2px 6px; border-radius: 3px; font-size: 9px; font-weight: 600; background: #fecaca; color: #991b1b; }}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="meta">{venue_name}<br>{datetime.now().strftime("%d %b %Y %H:%M")}</div>
</div>
{body}
<div class="footer">
  <span>Generated by Restin.ai</span>
  <span>Page 1</span>
</div>
</body>
</html>"""


# ═══════════════════════ 6.1 INGREDIENT LIST ═══════════════════════

@router.get("/venues/{venue_id}/ingredients")
async def print_ingredient_list(
    venue_id: str,
    category: str = Query(None),
    current_user: dict = Depends(get_current_user)
):
    """Print-ready HTML ingredient list with cost and stock info."""
    await check_venue_access(current_user, venue_id)

    query = {"venue_id": venue_id}
    if category:
        query["category"] = category

    items = await db.inventory_items.find(
        query, {"_id": 0}
    ).sort("name", 1).to_list(5000)

    venue = await db.venues.find_one({"id": venue_id}, {"name": 1, "_id": 0})
    venue_name = venue.get("name", "") if venue else ""

    rows = ""
    total_value = 0
    for i, item in enumerate(items, 1):
        name = item.get("name", item.get("item_name", ""))
        stock = item.get("current_stock", item.get("stock_level", 0)) or 0
        cost = item.get("cost", item.get("unit_cost", 0)) or 0
        unit = item.get("unit", "")
        cat = item.get("category", "")
        supplier = item.get("supplier", item.get("preferred_supplier", ""))
        value = stock * cost
        total_value += value

        stock_badge = "badge-green" if stock > (item.get("min_stock", 5) or 5) else "badge-red"

        rows += f"""<tr>
            <td>{i}</td>
            <td><strong>{name}</strong></td>
            <td>{cat}</td>
            <td>{unit}</td>
            <td><span class="badge {stock_badge}">{stock:.1f}</span></td>
            <td>€{cost:.2f}</td>
            <td>€{value:.2f}</td>
            <td>{supplier}</td>
        </tr>"""

    body = f"""
    <table>
        <thead><tr>
            <th>#</th><th>Ingredient</th><th>Category</th><th>Unit</th>
            <th>Stock</th><th>Unit Cost</th><th>Stock Value</th><th>Supplier</th>
        </tr></thead>
        <tbody>{rows}</tbody>
    </table>
    <div class="totals">Total Items: {len(items)} | Total Stock Value: €{total_value:.2f}</div>
    """

    return HTMLResponse(_html_wrapper("Ingredient List", body, venue_name))


# ═══════════════════════ 6.2 RECIPE CARD ═══════════════════════

@router.get("/venues/{venue_id}/recipes/{recipe_id}")
async def print_recipe_card(
    venue_id: str,
    recipe_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Print-ready HTML recipe card with ingredients, cost breakdown, allergens."""
    await check_venue_access(current_user, venue_id)

    recipe = await db.recipes.find_one(
        {"id": recipe_id, "venue_id": venue_id}, {"_id": 0}
    )
    if not recipe:
        raise HTTPException(404, "Recipe not found")

    venue = await db.venues.find_one({"id": venue_id}, {"name": 1, "_id": 0})
    venue_name = venue.get("name", "") if venue else ""

    # Info section
    cost = recipe.get("cost_analysis") or {}
    info_kv = f"""
    <div class="kv"><span class="label">Category:</span><span>{recipe.get("category", "-")}</span></div>
    <div class="kv"><span class="label">Cuisine:</span><span>{recipe.get("cuisine", "-")}</span></div>
    <div class="kv"><span class="label">Type:</span><span>{recipe.get("recipe_type", "-")}</span></div>
    <div class="kv"><span class="label">Servings:</span><span>{recipe.get("servings", 1)}</span></div>
    <div class="kv"><span class="label">Prep Time:</span><span>{recipe.get("prep_time_min", recipe.get("prep_time_minutes", "-"))} min</span></div>
    <div class="kv"><span class="label">Cook Time:</span><span>{recipe.get("cook_time_min", recipe.get("cook_time_minutes", "-"))} min</span></div>
    <div class="kv"><span class="label">Difficulty:</span><span>{"★" * recipe.get("difficulty", 1)}</span></div>
    <div class="kv"><span class="label">Yield:</span><span>{recipe.get("yield_pct", 100)}%</span></div>
    <div class="kv"><span class="label">Sell Price:</span><span>€{recipe.get("sell_price", 0):.2f}</span></div>
    <div class="kv"><span class="label">Cost/Serving:</span><span>€{cost.get("cost_per_serving", 0):.4f}</span></div>
    <div class="kv"><span class="label">Food Cost %:</span><span>{cost.get("food_cost_pct", "-")}%</span></div>
    """

    # Allergens
    allergens = recipe.get("allergens", {})
    allergen_badges = ""
    for a, v in allergens.items():
        if v:
            allergen_badges += f'<span class="allergen-badge">{a}</span>'
    if allergen_badges:
        allergen_badges = f'<div class="allergens">{allergen_badges}</div>'

    # Ingredients table
    ing_rows = ""
    for j, ing in enumerate(recipe.get("ingredients", []), 1):
        name = ing.get("name", ing.get("item_name", ""))
        qty = ing.get("net_qty", ing.get("quantity", 0))
        unit = ing.get("unit", "")
        waste = ing.get("waste_pct", 0)
        ucost = ing.get("unit_cost", ing.get("cost_per_unit", 0))
        tcost = ing.get("total_cost", 0)
        ing_type = ing.get("type", "ingredient")
        badge = '<span class="badge badge-yellow">SUB</span>' if ing_type == "sub_recipe" else ""

        ing_rows += f"""<tr>
            <td>{j}</td><td>{name} {badge}</td><td>{qty:.2f} {unit}</td>
            <td>{waste}%</td><td>€{ucost:.4f}</td><td>€{tcost:.4f}</td>
        </tr>"""

    # Steps
    steps_html = ""
    steps = recipe.get("steps") or recipe.get("composition") or ""
    if steps:
        steps_html = f'<div class="recipe-section"><h2>Preparation</h2><p>{steps}</p></div>'
    elif recipe.get("instructions"):
        steps_html = '<div class="recipe-section"><h2>Steps</h2><ol>' + \
            "".join(f"<li>{s}</li>" for s in recipe["instructions"]) + '</ol></div>'

    # Storage
    storage_html = ""
    if recipe.get("storage_conditions") or recipe.get("shelf_life_days"):
        storage_html = f"""<div class="recipe-section"><h2>Storage</h2>
            <div class="kv"><span class="label">Conditions:</span><span>{recipe.get("storage_conditions", "-")}</span></div>
            <div class="kv"><span class="label">Shelf Life:</span><span>{recipe.get("shelf_life_days", "-")} days</span></div>
            <div class="kv"><span class="label">Perishable:</span><span>{"Yes" if recipe.get("is_perishable") else "No"}</span></div>
        </div>"""

    body = f"""
    {info_kv}
    {allergen_badges}

    <div class="recipe-section">
    <h2>Ingredients</h2>
    <table>
        <thead><tr><th>#</th><th>Ingredient</th><th>Qty</th><th>Waste</th><th>Unit Cost</th><th>Total</th></tr></thead>
        <tbody>{ing_rows}</tbody>
    </table>
    <div class="totals">Total Cost: €{cost.get("total_cost", 0):.2f}</div>
    </div>

    {steps_html}
    {storage_html}
    """

    title = f"Recipe Card — {recipe.get('recipe_name', '')}"
    return HTMLResponse(_html_wrapper(title, body, venue_name))


# ═══════════════════════ 6.3 STOCK COUNT SHEET ═══════════════════════

@router.get("/venues/{venue_id}/stock-count")
async def print_stock_count_sheet(
    venue_id: str,
    category: str = Query(None),
    current_user: dict = Depends(get_current_user)
):
    """Print blank stock count sheet for physical counting."""
    await check_venue_access(current_user, venue_id)

    query = {"venue_id": venue_id}
    if category:
        query["category"] = category

    items = await db.inventory_items.find(
        query, {"_id": 0}
    ).sort("name", 1).to_list(5000)

    venue = await db.venues.find_one({"id": venue_id}, {"name": 1, "_id": 0})
    venue_name = venue.get("name", "") if venue else ""

    rows = ""
    for i, item in enumerate(items, 1):
        name = item.get("name", item.get("item_name", ""))
        unit = item.get("unit", "")
        cat = item.get("category", "")
        system_stock = item.get("current_stock", item.get("stock_level", 0)) or 0

        rows += f"""<tr>
            <td>{i}</td>
            <td><strong>{name}</strong></td>
            <td>{cat}</td>
            <td>{unit}</td>
            <td style="color:#a1a1aa">{system_stock:.1f}</td>
            <td style="width:80px; border-bottom: 1px dashed #71717a"></td>
            <td style="width:80px; border-bottom: 1px dashed #71717a"></td>
            <td style="width:60px"></td>
        </tr>"""

    body = f"""
    <p style="margin-bottom:12px; color:#71717a">Date: _______________ &nbsp; Counted by: _______________ &nbsp; Verified by: _______________</p>
    <table>
        <thead><tr>
            <th>#</th><th>Item</th><th>Category</th><th>Unit</th>
            <th>System</th><th>Counted</th><th>Variance</th><th>Notes</th>
        </tr></thead>
        <tbody>{rows}</tbody>
    </table>
    <div class="totals">Total Items: {len(items)}</div>
    <p style="margin-top: 30px; color: #71717a;">Signature: _______________ &nbsp; Date: _______________</p>
    """

    return HTMLResponse(_html_wrapper("Stock Count Sheet", body, venue_name))


# ═══════════════════════ 6.4 PURCHASE ORDER ═══════════════════════

@router.get("/venues/{venue_id}/purchase-orders/{po_id}")
async def print_purchase_order(
    venue_id: str,
    po_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Print-ready purchase order document."""
    await check_venue_access(current_user, venue_id)

    po = await db.purchase_orders.find_one(
        {"id": po_id, "venue_id": venue_id}, {"_id": 0}
    )
    if not po:
        raise HTTPException(404, "Purchase order not found")

    venue = await db.venues.find_one({"id": venue_id}, {"name": 1, "address": 1, "_id": 0})
    venue_name = venue.get("name", "") if venue else ""
    venue_addr = venue.get("address", "") if venue else ""

    # Supplier info
    supplier = po.get("supplier", {})
    if isinstance(supplier, str):
        supplier = {"name": supplier}

    supplier_html = f"""
    <div style="display:flex; justify-content:space-between; margin-bottom:16px;">
        <div>
            <strong>From:</strong><br>{venue_name}<br>{venue_addr}
        </div>
        <div style="text-align:right">
            <strong>To:</strong><br>{supplier.get("name", po.get("supplier_name", ""))}<br>
            {supplier.get("email", "")}<br>{supplier.get("phone", "")}
        </div>
    </div>
    <div class="kv"><span class="label">PO Number:</span><span>{po.get("po_number", po.get("id", "")[:8])}</span></div>
    <div class="kv"><span class="label">Status:</span><span>{po.get("status", "Draft")}</span></div>
    <div class="kv"><span class="label">Order Date:</span><span>{po.get("created_at", "")[:10]}</span></div>
    <div class="kv"><span class="label">Expected Delivery:</span><span>{po.get("expected_delivery", "-")}</span></div>
    """

    # Line items
    items_rows = ""
    total = 0
    for j, item in enumerate(po.get("items", po.get("line_items", [])), 1):
        name = item.get("name", item.get("item_name", ""))
        qty = item.get("quantity", 0)
        unit = item.get("unit", "")
        price = item.get("unit_price", item.get("price", 0)) or 0
        line_total = qty * price
        total += line_total

        items_rows += f"""<tr>
            <td>{j}</td><td>{name}</td><td>{qty} {unit}</td>
            <td>€{price:.2f}</td><td>€{line_total:.2f}</td>
        </tr>"""

    body = f"""
    {supplier_html}

    <table style="margin-top:16px">
        <thead><tr><th>#</th><th>Item</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead>
        <tbody>{items_rows}</tbody>
    </table>
    <div class="totals">Grand Total: €{total:.2f}</div>

    <div style="margin-top: 40px; display:flex; justify-content:space-between;">
        <div>Authorized by: _______________</div>
        <div>Date: _______________</div>
    </div>
    """

    title = f"Purchase Order — {po.get('po_number', po_id[:8])}"
    return HTMLResponse(_html_wrapper(title, body, venue_name))


# ═══════════════════════ 6.5 EXCEL EXPORT (COMPETITOR FORMAT) ═══════════════════════

@router.get("/venues/{venue_id}/export/ingredients")
async def export_ingredients_excel(
    venue_id: str,
    format: str = Query("csv", description="csv or json"),
    current_user: dict = Depends(get_current_user)
):
    """Export ingredients in competitor-compatible CSV format."""
    await check_venue_access(current_user, venue_id)

    items = await db.inventory_items.find(
        {"venue_id": venue_id}, {"_id": 0}
    ).sort("name", 1).to_list(5000)

    COLUMNS = [
        "item_id", "name", "category", "unit", "cost", "current_stock",
        "min_stock", "max_stock", "supplier", "allergens", "storage_type",
        "organic", "description", "image_url", "status"
    ]

    if format == "json":
        return JSONResponse(
            content={"items": items, "count": len(items)},
            headers={"Content-Disposition": f"attachment; filename=ingredients_{venue_id}.json"}
        )

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=COLUMNS, extrasaction="ignore")
    writer.writeheader()

    for item in items:
        allergens_val = item.get("allergens", [])
        if isinstance(allergens_val, list):
            allergens_str = ";".join(allergens_val)
        elif isinstance(allergens_val, dict):
            allergens_str = ";".join(k for k, v in allergens_val.items() if v)
        else:
            allergens_str = str(allergens_val)

        row = {
            "item_id": item.get("item_id", item.get("id", "")),
            "name": item.get("name", item.get("item_name", "")),
            "category": item.get("category", ""),
            "unit": item.get("unit", ""),
            "cost": item.get("cost", item.get("unit_cost", 0)),
            "current_stock": item.get("current_stock", item.get("stock_level", 0)),
            "min_stock": item.get("min_stock", ""),
            "max_stock": item.get("max_stock", ""),
            "supplier": item.get("supplier", item.get("preferred_supplier", "")),
            "allergens": allergens_str,
            "storage_type": item.get("storage_type", ""),
            "organic": item.get("organic", ""),
            "description": item.get("description", ""),
            "image_url": item.get("image_url", ""),
            "status": item.get("status", "active"),
        }
        writer.writerow(row)

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=ingredients_{venue_id}.csv"}
    )


@router.get("/venues/{venue_id}/export/stock-report")
async def export_stock_report(
    venue_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Export stock report with current levels, values, and variance."""
    await check_venue_access(current_user, venue_id)

    items = await db.inventory_items.find(
        {"venue_id": venue_id}, {"_id": 0}
    ).sort("name", 1).to_list(5000)

    COLUMNS = [
        "item_id", "name", "category", "unit",
        "current_stock", "min_stock", "cost",
        "stock_value", "stock_status", "last_updated"
    ]

    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=COLUMNS, extrasaction="ignore")
    writer.writeheader()

    for item in items:
        stock = item.get("current_stock", item.get("stock_level", 0)) or 0
        cost = item.get("cost", item.get("unit_cost", 0)) or 0
        min_s = item.get("min_stock", 0) or 0
        status = "OK" if stock > min_s else ("LOW" if stock > 0 else "OUT")

        writer.writerow({
            "item_id": item.get("item_id", item.get("id", "")),
            "name": item.get("name", item.get("item_name", "")),
            "category": item.get("category", ""),
            "unit": item.get("unit", ""),
            "current_stock": stock,
            "min_stock": min_s,
            "cost": cost,
            "stock_value": round(stock * cost, 2),
            "stock_status": status,
            "last_updated": item.get("updated_at", ""),
        })

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=stock_report_{venue_id}.csv"}
    )
