'use client';

import React from 'react';
import { Download } from 'lucide-react';
import { Button } from '@antigravity/ui';

interface PDFExportButtonProps {
    title: string;
    content: string;
    className?: string;
}

export default function PDFExportButton({ title, content, className }: PDFExportButtonProps) {
    const handleExport = () => {
        const win = window.open('', '_blank');
        if (!win) return;

        win.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: 'Courier New', monospace; padding: 40px; color: #111827; line-height: 1.6; background: #fff; }
            h1 { color: #000; border-bottom: 2px solid #000; padding-bottom: 10px; text-transform: uppercase; letter-spacing: 2px; }
            h2 { color: #333; margin-top: 30px; text-decoration: underline; }
            h3 { color: #555; }
            .meta { font-size: 10px; color: #666; margin-bottom: 20px; border: 1px solid #ccc; padding: 5px; }
            pre { background: #f3f4f6; padding: 15px; border-radius: 0; border: 1px solid #ccc; overflow-x: auto; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; border: 1px solid #000; }
            th, td { border: 1px solid #000; padding: 8px; text-align: left; }
            th { background-color: #eee; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="meta">GENERATED BY RESTIN.AI | CLASSIFIED: INTERNAL USE ONLY | ${new Date().toISOString()}</div>
          <h1>${title}</h1>
          ${content}
        </body>
      </html>
    `);
        win.document.close();
        win.focus();
        setTimeout(() => win.print(), 250);
    };

    return (
        <Button
            onClick={handleExport}
            className={className}
            variant="outline"
            size="sm"
        >
            <Download className="h-4 w-4 mr-2" />
            Export PDF
        </Button>
    );
}
